language:
  node_js
node_js:
  "node"
install:
  - npm install
  - npm install --save-dev nyc
  - npm install -g mocha
  - npm install --save-dev coveralls
script:
  - npm test
after_success:
  - npm run coveralls
env:
  - is_in_travis=true