language:
  node_js
node_js:
  "node"
install:
  - npm install
  - npm install --save-dev nyc
  - npm install -g mocha
  - npm install --save-dev coveralls
script:
  - npm test app/*
after_success:
  - npm run coveralls